# Generated by Django 6.0 on 2026-01-05 11:58

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_token_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 5, 11, 58, 29, 360949, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.TextField(db_index=True, default=uuid.uuid4),
        ),
    ]
