# Generated by Django 6.0 on 2026-01-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_token_created_at_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
