# Generated by Django 6.0 on 2026-01-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_token_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='os',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
