# Generated by Django 6.0 on 2026-01-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_token_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='os',
            field=models.CharField(max_length=50),
        ),
    ]
