# Generated by Django 6.0 on 2026-01-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akira', '0002_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='animeId',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
